<a href="https://colab.research.google.com/github/libanabduba/Deep-Learning-Lab-AAU/blob/main/DL_Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [9]:
torch.manual_seed(27)

In [10]:
input = torch.rand(4)
weight = torch.rand(4)
bias = torch.rand(1)

(input, weight, bias)

(tensor([0.9847, 0.0852, 0.5334, 0.2196]),
 tensor([0.2617, 0.7972, 0.2088, 0.4545]),
 tensor([0.1455]))

In [12]:
output = 0
for x, w in zip(input, weight):
  output += x * w

output += bias[0]

output

tensor(0.6823)

In [11]:
torch.matmul(input, weight) + bias

tensor([0.6823])

#Layer of Neurons

In [24]:
weight2 = torch.rand(size = (5,4))
input2 =  torch.rand(4)
input2 = input2.t()
bias2 = torch.rand(5)

In [25]:
input3 = torch.matmul(input2, weight2.T) + bias2

In [26]:
weight3 = torch.rand(size = (2,5))
bias3 = torch.rand(2)

torch.matmul(input3, weight3.T) + bias3

tensor([6.9785, 5.5859])

#Layer of Neurons and Batch of Data

In [29]:
input_1 = torch.rand((32,4))
weight_1 = torch.rand((5,4))
bias_1 = torch.rand(5)

In [30]:
output_1 = torch.matmul(input_1, weight_1.T) + bias_1

In [32]:
output_1.shape

torch.Size([32, 5])

In [37]:
weight_2 = torch.rand((5,5))
bias_2 = torch.rand(5)

In [38]:
output_2 = torch.matmul(output_1, weight_2.T) + bias_2
output_2.shape

torch.Size([32, 5])

In [39]:
weight_3 = torch.rand((3,5))
bias_3 = torch.rand(3)

In [40]:
output_3 = torch.matmul(output_2, weight_3.T) + bias_3
output_3.shape

torch.Size([32, 3])

#Coding Neural Network with OOP

In [46]:
class DenseLayer:

  def __init__(self, n_inputs, n_neurons):
    # Initialize weights and biase
    self.weight = 0.01 * torch.rand((n_neurons,n_inputs))
    self.bias = torch.zeros((1,n_neurons))


  def forward(self, inputs):
    # Calculate output values from inputs, weights and biases
    self.output = torch.matmul(inputs, self.weight.T) + self.bias


In [47]:
# create data

X =  torch.rand((2,4))

In [48]:
# Model Creation
layer1 = DenseLayer(4,6)
layer2 = DenseLayer(6, 5)
output_layer = DenseLayer(5, 2)

In [50]:
layer1.forward(X)
layer2.forward(layer1.output)
output_layer.forward(layer2.output)


In [51]:
output_layer.output

tensor([[5.8813e-06, 8.1237e-06],
        [6.3222e-06, 8.6889e-06]])